version: '3.8'

services:
  main:
    build:
      context: .
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - HTTP_PORT=3000
      - LAMBDA_PORT=4000
    volumes:
      - ./:/app
      - main:/app/node_modules
    # healthcheck to warmup the lambda
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - voca-mastrey-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: voca_mastery

volumes:
  main:
  voca-mastrey-mysql-data: